### ISSUE TITLE
td-agent.conf is not recognizing the jmx plugin

### ISSUE THREAD

**Issue by amanjain08** [niyonmaruz/fluent-plugin-jmx#4]
I am trying the sample code that you have given but the fluentd is not able to recognize the **jmx** plugin.

> td-agent.conf
```
<source>
 @type jmx
  tag jmx.memory
  url http://127.0.0.1:8778/jolokia
  mbean java.lang:type=Memory
  attribute HeapMemoryUsage
  interval 1
  inner_path used
</source>

<match jmx.**>
@type stdout
</match>
```

Error :
`config error file="/etc/td-agent/td-agent.conf" error_class=Fluent::ConfigError error="Unknown input plugin 'jmx'. Run 'gem search -rd fluent-plugin' to find plugins"`

**Comment by niyonmaruz** [comment]
@amanjain08 In that case, you need to install it by Gem used by td-agent.

    $ sudo /opt/td-agent/embedded/bin/fluent-gem install fluent-plugin-jmx

I've added this to README.

I confirmed that fluent-plugin-jmx can be started normally by td-agent.
And I fixed a bug that I found during this process.
https://rubygems.org/gems/fluent-plugin-jmx/versions/0.0.4

Please try the installation above.
Thanks!
